//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public long id { get; set; }
        public string name { get; set; }
        public string idno { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public System.DateTime dateCreated { get; set; }
    }
}
